//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial6
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntiCheatLog
    {
        public int LogId { get; set; }
        public int AttemptId { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string EventType { get; set; }
        public string BrowserData { get; set; }
    
        public virtual StudentAttempt StudentAttempt { get; set; }
    }
}
