//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial6
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttemptAnswer
    {
        public int AnswerId { get; set; }
        public int AttemptId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> SelectedOptionId { get; set; }
        public string TextResponse { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual StudentAttempt StudentAttempt { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
        public virtual Question Question { get; set; }
    }
}
