//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial6
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeAuditLog
    {
        public int AuditId { get; set; }
        public Nullable<int> AttemptId { get; set; }
        public Nullable<decimal> OldScore { get; set; }
        public Nullable<decimal> NewScore { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
        public string ChangedByUser { get; set; }
    }
}
