//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial6
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentAttempt()
        {
            this.AntiCheatLogs = new HashSet<AntiCheatLog>();
            this.AttemptAnswers = new HashSet<AttemptAnswer>();
        }
    
        public int AttemptId { get; set; }
        public int ExamId { get; set; }
        public int UserId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> TotalScore { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntiCheatLog> AntiCheatLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttemptAnswer> AttemptAnswers { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual User User { get; set; }
    }
}
